on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - created
  workflow_dispatch:

name: build-deploy-to-cdn
jobs:
  build:
    outputs:
      public_url: ${{ steps.install.outputs.public_url }}
      public_path: ${{ steps.install.outputs.public_path }}
      dcl_ecs_s3_bucket_key: ${{ steps.publish_dcl_ecs.outputs.s3-bucket-key }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: set package.json version
        uses: menduz/oddish-action@master
        with:
          deterministic-snapshot: true
          only-update-versions: true

      - id: install
        name: install
        run: npm ci

      - name: build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: npm run build

      - name: test
        run: npm run test

      - name: copy package.json
        run: cp "./package.json" "./public/package.json"

      - name: publish npm package
        uses: menduz/oddish-action@master
        with:
          scope: "@dcl"
          access: public
          cwd: './public'

          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true

          ## inform gitlab after publishing to proceed with CDN propagation and rollouts
          # 104 == https://dcl.tools/pipelines/static-sites-pipeline
          gitlab-pipeline-url: ${{ secrets.GITLAB_CDN_DEPLOYER_URL }}
          gitlab-token: ${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }}

          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: '@dcl/docs-site/branch/${{ github.head_ref || github.ref }}'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}

  notify_deployment:
    needs: [build]
    if: ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    name: Deployment Notification
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Test this pull request
      - name: Generate S3 URL
        id: url-generator
        run: |
          body="https://sdk-team-cdn.decentraland.org/${{ needs.build.outputs.dcl_ecs_s3_bucket_key }}"
          echo ::set-output name=body::$body
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test this pull request
            This branch can be previewed at ${{ steps.url-generator.outputs.body }}
          edit-mode: replace
